const classNames = {
    "ACR": "Acrobat",
    "ALC": "Alchemist",
    "ARC": "Archer",
    "ASN": "Assassin",
    "BAR": "Bard",
    "BER": "Berserker",
    "BLO": "Bloodmage",
    "BUI": "Builder",
    "CIV": "Civilian",
    "DAS": "Dasher",
    "DEF": "Defender",
    "ENC": "Enchanter",
    "ENG": "Engineer",
    "FAR": "Farmer",
    "HAN": "Handyman",
    "HEA": "Healer",
    "HUN": "Hunter",
    "ICE": "Iceman",
    "IMM": "Immobilizer",
    "LUM": "Lumberjack",
    "MER": "Mercenary",
    "MIN": "Miner",
    "NIN": "Ninja",
    "PYR": "Pyro",
    "RIF": "Rift Walker",
    "ROB": "Robin Hood",
    "SCP": "Scorpio",
    "SCO": "Scout",
    "SNI": "Sniper",
    "SPI": "Spider",
    "SPY": "Spy",
    "SUC": "Succubus",
    "SWA": "Swapper",
    "THO": "Thor",
    "TIN": "Tinkerer",
    "TRA": "Transporter",
    "VAM": "Vampire",
    "WAR": "Warrior",
    "WIZ": "Wizard"
}